# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayase.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.chatArea = QtWidgets.QTextEdit(self.widget_4)
        self.chatArea.setReadOnly(True)
        self.chatArea.setObjectName("chatArea")
        self.gridLayout_4.addWidget(self.chatArea, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_4, 1, 1, 1, 2)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputMensaje = QtWidgets.QLineEdit(self.widget_2)
        self.inputMensaje.setObjectName("inputMensaje")
        self.gridLayout_2.addWidget(self.inputMensaje, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_2, 2, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.botonEnviar = QtWidgets.QPushButton(self.widget_3)
        self.botonEnviar.setObjectName("botonEnviar")
        self.gridLayout_3.addWidget(self.botonEnviar, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 2, 2, 2, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.botonTema = QtWidgets.QPushButton(self.widget)
        self.botonTema.setObjectName("botonTema")
        self.gridLayout.addWidget(self.botonTema, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 2, 1, 1)
        self.LabelTitulo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LabelTitulo.setFont(font)
        self.LabelTitulo.setObjectName("LabelTitulo")
        self.gridLayout_5.addWidget(self.LabelTitulo, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.botonTema.setText(_translate("MainWindow", "🌙"))
        self.LabelTitulo.setText(_translate("MainWindow", "Ayase"))
