# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayase.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setObjectName("labelTitulo")
        self.gridLayout.addWidget(self.labelTitulo, 0, 0, 1, 3)
        self.chatArea = QtWidgets.QTextEdit(self.centralwidget)
        self.chatArea.setReadOnly(True)
        self.chatArea.setObjectName("chatArea")
        self.gridLayout.addWidget(self.chatArea, 1, 0, 1, 3)
        self.inputMensaje = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMensaje.setObjectName("inputMensaje")
        self.gridLayout.addWidget(self.inputMensaje, 2, 0, 1, 1)
        self.botonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.botonEnviar.setObjectName("botonEnviar")
        self.gridLayout.addWidget(self.botonEnviar, 2, 1, 1, 1)
        self.botonTema = QtWidgets.QPushButton(self.centralwidget)
        self.botonTema.setObjectName("botonTema")
        self.gridLayout.addWidget(self.botonTema, 2, 2, 1, 1)
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setObjectName("botonAtras")
        self.gridLayout.addWidget(self.botonAtras, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ayase - Asistente"))
        self.labelTitulo.setText(_translate("MainWindow", "Ayase - Asistente Personal"))
        self.inputMensaje.setPlaceholderText(_translate("MainWindow", "Escribí tu mensaje..."))
        self.botonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.botonTema.setText(_translate("MainWindow", "🌙"))
        self.botonTema.setToolTip(_translate("MainWindow", "Cambiar tema"))
        self.botonAtras.setText(_translate("MainWindow", "← Volver"))
        self.botonAtras.setToolTip(_translate("MainWindow", "Volver a selección de conexión"))
